-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "VersionInfo" (
	"Version" bigint NOT NULL,
	"AppliedOn" timestamp,
	"Description" varchar(1024)
);
--> statement-breakpoint
CREATE TABLE "level" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "level_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hash" text NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone,
	CONSTRAINT "level_pk" UNIQUE("hash")
);
--> statement-breakpoint
CREATE TABLE "level_item" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "level_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_level" integer NOT NULL,
	"workshop_id" numeric NOT NULL,
	"author_id" numeric NOT NULL,
	"name" text NOT NULL,
	"image_url" text NOT NULL,
	"file_author" text NOT NULL,
	"file_uid" text NOT NULL,
	"validation_time_author" real NOT NULL,
	"validation_time_gold" real NOT NULL,
	"validation_time_silver" real NOT NULL,
	"validation_time_bronze" real NOT NULL,
	"deleted" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "level_metadata" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "level_metadata_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_level" integer NOT NULL,
	"amount_checkpoints" integer NOT NULL,
	"amount_finishes" integer NOT NULL,
	"amount_blocks" integer NOT NULL,
	"type_ground" integer NOT NULL,
	"type_skybox" integer NOT NULL,
	"blocks" jsonb NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "level_points" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "level_points_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"points" integer NOT NULL,
	"id_level" integer NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "level_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workshop_id" numeric NOT NULL,
	"uid" text,
	"hash" text,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "personal_best_global" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "personal_bests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_record" integer NOT NULL,
	"id_user" integer NOT NULL,
	"id_level" integer NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "user_points" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "player_points_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"points" integer NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone,
	"rank" integer DEFAULT 0 NOT NULL,
	"world_records" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "auth" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer,
	"access_token" text,
	"access_token_expiry" bigint,
	"refresh_token" text,
	"refresh_token_expiry" bigint,
	"type" integer,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "record" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"time" real NOT NULL,
	"game_version" varchar(255) NOT NULL,
	"id_level" integer NOT NULL,
	"mod_version" varchar(255) NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone,
	"splits" real[],
	"speeds" real[]
);
--> statement-breakpoint
CREATE TABLE "record_media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_record" integer NOT NULL,
	"ghost_url" text,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "upvote" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upvotes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"id_level" integer NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"steam_name" varchar(255),
	"banned" boolean DEFAULT false NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone,
	"steam_id" numeric,
	"discord_id" numeric
);
--> statement-breakpoint
CREATE TABLE "version" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"minimum" text,
	"latest" text,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "favorite" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "favorites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone,
	"id_level" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vote" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "vote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_user" integer NOT NULL,
	"id_level" integer NOT NULL,
	"value" integer NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "world_record_global" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "world_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_record" integer NOT NULL,
	"id_level" integer NOT NULL,
	"date_created" timestamp with time zone NOT NULL,
	"date_updated" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "level_item" ADD CONSTRAINT "level_item_id_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "level_metadata" ADD CONSTRAINT "level_metadata_id_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "level_points" ADD CONSTRAINT "level_points_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_best_global" ADD CONSTRAINT "personal_best_global_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_best_global" ADD CONSTRAINT "personal_bests_global_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_best_global" ADD CONSTRAINT "personal_bests_global_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_points" ADD CONSTRAINT "player_points_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "auth" ADD CONSTRAINT "auth_user_foreign" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "record" ADD CONSTRAINT "record_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "record" ADD CONSTRAINT "records_user_foreign" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "record_media" ADD CONSTRAINT "media_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upvote" ADD CONSTRAINT "upvote_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upvote" ADD CONSTRAINT "upvotes_user_foreign" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "favorite" ADD CONSTRAINT "favorite_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "favorite" ADD CONSTRAINT "favorites_user_foreign" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_id_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vote" ADD CONSTRAINT "vote_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_record_global" ADD CONSTRAINT "world_record_global_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "world_record_global" ADD CONSTRAINT "world_records_global_record_fkey" FOREIGN KEY ("id_record") REFERENCES "public"."record"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "UC_Version" ON "VersionInfo" USING btree ("Version" int8_ops);--> statement-breakpoint
CREATE INDEX "IX_personal_bests_record" ON "personal_best_global" USING btree ("id_record" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_personal_bests_user" ON "personal_best_global" USING btree ("id_user" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_player_points_user" ON "user_points" USING btree ("id_user" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_auth_user" ON "auth" USING btree ("id_user" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_records_user" ON "record" USING btree ("id_user" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_media_record" ON "record_media" USING btree ("id_record" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_upvotes_user" ON "upvote" USING btree ("id_user" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_favorites_user" ON "favorite" USING btree ("id_user" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_world_records_record" ON "world_record_global" USING btree ("id_record" int4_ops);--> statement-breakpoint
CREATE VIEW "public"."sampled_favorite" AS (SELECT id, id_user, date_created, date_updated, id_level FROM favorite TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_level" AS (SELECT id, hash, date_created, date_updated FROM level TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_level_item" AS (SELECT id, id_level, workshop_id, author_id, name, image_url, file_author, file_uid, validation_time_author, validation_time_gold, validation_time_silver, validation_time_bronze, deleted, created_at, updated_at, date_created, date_updated FROM level_item TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_level_metadata" AS (SELECT id, id_level, amount_checkpoints, amount_finishes, amount_blocks, type_ground, type_skybox, blocks, date_created, date_updated FROM level_metadata TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_level_points" AS (SELECT id, points, id_level, date_created, date_updated FROM level_points TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_level_request" AS (SELECT id, workshop_id, uid, hash, date_created, date_updated FROM level_request TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_personal_best_global" AS (SELECT id, id_record, id_user, id_level, date_created, date_updated FROM personal_best_global TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_record" AS (SELECT id, id_user, "time", game_version, id_level, mod_version, date_created, date_updated, splits, speeds FROM record TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_record_media" AS (SELECT id, id_record, ghost_url, date_created, date_updated FROM record_media TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_upvote" AS (SELECT id, id_user, id_level, date_created, date_updated FROM upvote TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_user" AS (SELECT id, steam_name, banned, date_created, date_updated, steam_id, discord_id FROM "user" TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_user_points" AS (SELECT id, id_user, points, date_created, date_updated, rank, world_records FROM user_points TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_version" AS (SELECT id, minimum, latest, date_created, date_updated FROM version TABLESAMPLE bernoulli (1));--> statement-breakpoint
CREATE VIEW "public"."sampled_world_record_global" AS (SELECT id, id_record, id_level, date_created, date_updated FROM world_record_global TABLESAMPLE bernoulli (1));
*/